### ISSUE TITLE
Implement exercise submission page

### ISSUE THREAD

**Issue by rolandgeider** [wger-project/react#261]
We need a page that allows users to contribute new exercises. We need a multi step form that guides the user in the process. If there are any validation errors in a step, the user should not be able to continue. Also, the user should be able to go back and edit already added data

(Screenshots are from the flutter app)

## step 1
basic  exercise data such as categories as well as the name or aliases (alternative names)
![Screenshot_1652701209](https://user-images.githubusercontent.com/2280729/169871120-b366a175-3b93-498a-ae9a-12900f2f9504.png)

- [x] name is required, min chars 5, max chars 40
- [x]  alternative names: optional but if entered they should be validated the same as the name
- [x]  category: required, by default nothing is selected
- [x]  muscles and secondary muscles: optional (it would be good to make the validation aware that a specific muscle was selected as main and secondary, which is obviously not correct)
- [x]  need to implement an overview widget to show the selected muscles #292 

## step 2
 variations
![Screenshot_1652701281](https://user-images.githubusercontent.com/2280729/169871296-3644fc51-707d-4848-bf6e-2e7039b887ab.png)

- [x] the user can select a variation

## step 3
 description in English
![Screenshot_1652701290](https://user-images.githubusercontent.com/2280729/169871321-a53413a5-5795-48f8-a06a-f16745d45c23.png)

- [x] min length 40
- [ ] Add a simple html editor (can be done later): #307 

##  step 4
 translation
![Screenshot_1652701298](https://user-images.githubusercontent.com/2280729/169871372-5f6f0643-b2e5-4f08-ad05-936bf61321a8.png)
![Screenshot_1652701310](https://user-images.githubusercontent.com/2280729/169871403-fa207e3e-bd33-4ddb-8ce5-2b31b41c9785.png)

- [x] present a switch allowing the user to translate the exercise now
- [x] if the switch is clicked, the form is presented otherwise the user can simply continue
- [x] the forms for name, alternative names and description have the same validation rules as their counterparts in English
- [ ] Add a simple html editor for the description (can be done later): #307 

## step 5
images

![Screenshot_1652701315](https://user-images.githubusercontent.com/2280729/169871449-30471bbb-cbd7-4df1-90e1-55748e5cf415.png)

![Screenshot_1652701341](https://user-images.githubusercontent.com/2280729/169871458-15634b71-9b6a-4568-958e-262569d0d848.png)

- [x] the user is allowed to upload images, but this is optional. Ideally we would allow to drag and drop the images, but a simple upload button is also ok

What still needs to be done is check the profile and see if their email has been verified, otherwise they shouldn't be allowed to contribute the exercise: #293
